version: '3'

services:
  pysparkapi:
    build: pysparkapi/
    image: docker.io/jazi1999/bda-final-project-pysparkapi:latest
    ports:
      - 5000:5000
    networks:
      - deploy_network
    container_name: pysparkapi

  streamlitapi:
    build: streamlitapi/
    image: docker.io/jazi1999/bda-final-project-streamlitapi:latest
    depends_on:
      - pysparkapi
    ports:
      - 8501:8501
    networks:
      - deploy_network
    container_name: streamlitapi
networks:
  deploy_network:
    driver: bridge
